name: Daily Blocklist Update

on:
  schedule:
    - cron: '0 0 * * *' # Täglich um Mitternacht
  workflow_dispatch: # Erlaubt manuelles Starten über den "Actions" Tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Update Script
        run: python update_list.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Wir fügen einfach alles hinzu, was sich geändert hat (-A)
          git add -A
          # Commit nur, wenn es wirklich Änderungen gibt
          git commit -m "Update Blocklists $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
