name: Daily Blocklist Update

on:
  schedule:
    - cron: '0 0 * * *' # Täglich um Mitternacht
  workflow_dispatch: # Erlaubt manuelles Starten

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Update Script
        run: python update_list.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add combined_blocklist.txt
          git add lists/*.txt || echo "Keine neuen Listen gefunden"
          git commit -m "Update Blocklists $(date)" || echo "Keine Änderungen zum Committen"
          git push
