name: Daily Blocklist Update

on:
  schedule:
    - cron: '0 0 * * *' # Täglich um Mitternacht
  workflow_dispatch: # Erlaubt manuelles Starten

permissions:
  contents: write # WICHTIG: Erlaubt der Action, die whitelist.txt und Listen hochzuladen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Nutzt das Standard-Token für den Push

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Update Script
        run: python update_list.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          # Nur committen, wenn sich wirklich etwas geändert hat
          if ! git diff --quiet --cached; then
            git commit -m "TechRZN Auto-Update: $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
          fi
